apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nginx-production-alerts
  namespace: monitoring
  labels:
    release: kube-prom-stack
    app: nginx-production
    environment: production
spec:
  groups:
  - name: nginx-production
    rules:
    - alert: NginxHighErrorRate
      expr: rate(nginx_http_requests_total{status=~"5.."}[5m]) / rate(nginx_http_requests_total[5m]) > 0.05
      for: 2m
      labels:
        severity: critical
        component: nginx-production
      annotations:
        summary: "High error rate detected"
        description: "Error rate is {{ $value | humanizePercentage }}"
    
    - alert: NginxHighLatency
      expr: histogram_quantile(0.95, rate(nginx_http_request_duration_seconds_bucket[5m])) > 0.5
      for: 2m
      labels:
        severity: warning
        component: nginx-production
      annotations:
        summary: "High response latency detected"
        description: "95th percentile latency is {{ $value }}s"
    
    - alert: NginxHighCPUUsage
      expr: container_cpu_usage_seconds_total{container="nginx"} / container_spec_cpu_quota{container="nginx"} * 100 > 80
      for: 5m
      labels:
        severity: warning
        component: nginx-production
      annotations:
        summary: "High CPU usage detected"
        description: "CPU usage is {{ $value }}%"
    
    - alert: NginxHighMemoryUsage
      expr: container_memory_usage_bytes{container="nginx"} / container_spec_memory_limit_bytes{container="nginx"} * 100 > 85
      for: 5m
      labels:
        severity: warning
        component: nginx-production
      annotations:
        summary: "High memory usage detected"
        description: "Memory usage is {{ $value }}%"
    
    - alert: NginxPodDown
      expr: up{job="nginx-production"} == 0
      for: 1m
      labels:
        severity: critical
        component: nginx-production
      annotations:
        summary: "Nginx pod is down"
        description: "Nginx pod {{ $labels.pod }} is not responding" 