apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: prometheus
  ruleSelector:
    matchLabels:
      role: alert-rules
  resources:
    requests:
      memory: 400Mi
  additionalScrapeConfigs:
    - job_name: 'nginx-exporter'
      scrape_interval: 15s
      static_configs:
        - targets: ['nginx-exporter:9113']
  ruleFiles:
    - /nginx_rules.yml
