apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    events {}

    http {
        server {
            listen 80;
            location / {
                return 200 'Hello from NGINX\n';
            }

            # Metrics endpoint
            location /nginx_status {
                stub_status;
                allow 127.0.0.1;
                deny all;
            }
        }
    }
